### ISSUE TITLE
Responsive Design for Mobile UI of Web Pages

### ISSUE THREAD

**Issue by unclemfon** [zuri-training/auth_wiki_team_1_project#100]
Responsive Design for your previously assigned tasks

**Comment by olayinka12345** [comment]
Almost done

**Comment by Jeremy124124** [comment]
On it currently

**Comment by jben2122** [comment]
still in  progress and almost done

**Comment by Stanleycaleb** [comment]
Still working on it.

**Comment by theotherfaceofA** [comment]
I designed the mobile UI of the comments page for unathenticated users of the library.

https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1461%3A18495

**Comment by DesiignBro** [comment]
> Responsive Design for your previously assigned tasks

Completion rate set at 70% so far

**Comment by MeeYah66** [comment]
Completed.
I designed the mobile UI for the about us page.
https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1458%3A24932

**Comment by MakkyD** [comment]
completed!

**Comment by jben2122** [comment]
i designed the mobile UI for the documentation page
https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1458%3A23742

**Comment by theotherfaceofA** [comment]
I designed the mobile UI of the main library page for unathenticated users

https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1461%3A18104

**Comment by theotherfaceofA** [comment]
I worked on the mobile UI of the "view more" page for unathenticated users of the library

https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1490%3A19451
