### ISSUE TITLE
Implement Email Notification

### ISSUE THREAD

**Issue by unclemfon** [zuri-training/auth_wiki_team_1_project#104]

**Comment by adilimudassir** [comment]
Hey, zee. ANything yet? If you are having blockers, Edidiong can help

**Comment by zeelyha** [comment]
Yeah, I'm a bit confused on how start. If he can help that'll be great.

**Comment by technicaldee** [comment]
@zeelyha push the code you have so far to a branch and let me know the name of the branch

**Comment by zeelyha** [comment]
First of all, I don't even know where to put the code

**Comment by technicaldee** [comment]
Its okay @zeelyha ... Ive written code for email... The important question @themfon @adilimudassir , we are notifying the user after what action eg. is it after signup or login or comment etc... Let me know soonest to push the code asap

**Comment by zeelyha** [comment]
I thought the email notification was for password reset

**Comment by technicaldee** [comment]
if that is it, then i am done... Please @adilimudassir confirm... I have closed task
