### ISSUE TITLE
Design Mobile UI of Homepage for Responsiveness

### ISSUE THREAD

**Issue by DesiignBro** [zuri-training/auth_wiki_team_1_project#154]

**Comment by olayinka12345** [comment]
I worked on the Lo-Fi and Hi-Fi of the body of the homepage Mobile UI which also includes the about us, our core features and the contact us section of the page using the style guide that was provided.

Attached below is the Figma link to the Lo-Fi and Hi-Fi of the mobile Mobile Homepage Frame
Lo-Fi Link: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1591%3A31639
Hi-Fi: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1565%3A23657

**Comment by DesiignBro** [comment]
I designed for the Hero section of the Homepage UI as well. I designed for Lo-Fi and Hi-Fi also. Attached below are their respective Figma Links of the Mobile UI for Homepage

Hi-Fi: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1565%3A23657
Lo-Fi: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1591%3A31639
