### ISSUE TITLE
Design Mobile UI of Library Page for Responsiveness

### ISSUE THREAD

**Issue by DesiignBro** [zuri-training/auth_wiki_team_1_project#155]

**Comment by Jeremy124124** [comment]
I designed the authenticated user page of the library UI, links to desined page are seen below 
low-fi: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1626%3A21130
Hi-fi: https: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1625%3A21541

**Comment by theotherfaceofA** [comment]
I designed the authenticated user page of the library UI, links to designed pages are seen below
Lo-fi: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1626%3A21131
Hi-fi: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1625%3A21542
