### ISSUE TITLE
Design Mobile UI of Sign-in/Sign-up/Forget Password pages for Responsiveness

### ISSUE THREAD

**Issue by DesiignBro** [zuri-training/auth_wiki_team_1_project#156]

**Comment by MakkyD** [comment]
I also worked on the mobile UI's for my initially assigned task which was the SignUp, SignIn and Forgot password screen of which i delivered Both LowFidelity and HFidelity designs.

Attached below is the link to the LowFidelity Mobile UI's
Mobile-UI-LowFi    -    https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1602%3A20853

**Comment by MakkyD** [comment]
I finally worked on the Hi-Fidelity designs for the mobile UI's i was assigned to do- SignUp, SignIn and Forgot password screens.

Attached below is the link to the Hi-Fidelity Mobile UI's
Mobile-UI-HiFi  -https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1569%3A18749
