### ISSUE TITLE
Design Mobile UI of FAQ & About Us page for Responsiveness

### ISSUE THREAD

**Issue by DesiignBro** [zuri-training/auth_wiki_team_1_project#157]

**Comment by MeeYah66** [comment]
Completed. 
I created the lo-fi and high-fi for the mobile UI of the FAQs and About Us page.

About us hi-fi: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1583%3A31635

About us lo-fi: 
https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1625%3A20853

FAQs hi-fi: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1565%3A25676

FAQs lo-fi: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1591%3A32064
