### ISSUE TITLE
Design Terms and Condition page

### ISSUE THREAD

**Issue by DesiignBro** [zuri-training/auth_wiki_team_1_project#161]

**Comment by Favourjubilee** [comment]
Designed the Terms & Conditions Page.
Find attached below the links.

Did the Web Lo-Fi: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1591%3A34733
Did the Web Hi-Fi: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1565%3A20396
