### ISSUE TITLE
Design Mobile UI of Terms & Conditions page for Responsiveness

### ISSUE THREAD

**Issue by DesiignBro** [zuri-training/auth_wiki_team_1_project#162]

**Comment by Favourjubilee** [comment]
Designed the Mobile UI of terms and conditions page for responsiveness.
Find attached below the links.
Did the Lo-Fi Mobile: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1591%3A32619
Did the Hi-Fi Mobile: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1565%3A25822
