### ISSUE TITLE
Design Mobile UI of Get Support page for Responsiveness

### ISSUE THREAD

**Issue by DesiignBro** [zuri-training/auth_wiki_team_1_project#164]

**Comment by Olivia438** [comment]
I designed the get support page for mobile responsiveness
LOFI LINK
https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1591%3A32750
HIFI LINK
https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1565%3A25735

**Comment by Olivia438** [comment]
I designed the get support page for mobile responsiveness
LOFI LINK
https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1591%3A32750
HIFI LINK
https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1565%3A25735

**Comment by Olivia438** [comment]
I designed the get support page for mobile responsiveness
LOFI LINK
https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1591%3A32750
HIFI LINK
https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1565%3A25735
