### ISSUE TITLE
FAQ Design

### ISSUE THREAD

**Issue by DesiignBro** [zuri-training/auth_wiki_team_1_project#166]

**Comment by MeeYah66** [comment]
Completed.
I designed the sketches, lo-fi and hi-fi for the web UI of the FAQs page using the design system provided and inspirations from some FAQs pages on dribble.

Hi-fi: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1565%3A20444

Lo-fi: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1591%3A34687
