### ISSUE TITLE
About us Page Design

### ISSUE THREAD

**Issue by DesiignBro** [zuri-training/auth_wiki_team_1_project#169]

**Comment by MeeYah66** [comment]
I designed the lo-fi and the hero section of the hi-fi of the about us page

Lo-fi: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1625%3A20854

Hi-fi: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1583%3A31637
