### ISSUE TITLE
Design Library Page

### ISSUE THREAD

**Issue by DesiignBro** [zuri-training/auth_wiki_team_1_project#170]

**Comment by Jeremy124124** [comment]
I designed the desktop Web UI of the authenticated user on the Library page, below are the links to the frame
lo-fi figma link: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1603%3A20246
Hi-fi figma link: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1567%3A19093

**Comment by theotherfaceofA** [comment]
I worked on the desktop Web UI of the unauthenticated user on the Library page, below are links to the frames
Lo-fi figma link: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1722%3A20845
Hi-fi figma link: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1722%3A20846
