### ISSUE TITLE
Get Support page UI Design

### ISSUE THREAD

**Issue by DesiignBro** [zuri-training/auth_wiki_team_1_project#171]

**Comment by Olivia438** [comment]
LOFI LINK:  
https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1591%3A34621
HIFI LINK: 
  https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1565%3A20701
I designed the get support web page
