### ISSUE TITLE
Homepage UI Design

### ISSUE THREAD

**Issue by DesiignBro** [zuri-training/auth_wiki_team_1_project#172]

**Comment by olayinka12345** [comment]
I designed the Lo-Fi and Hi-Fi of the body of the homepage Web UI which includes the About us section, our core features and the contact us page

Attached below is the Figma link to the Lo-Fi and Hi-Fi of the Homepage Frame:
Lo-Fi Link: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1591%3A32879
Hi-Fi Link: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1565%3A18748

**Comment by DesiignBro** [comment]
I worked on the Hero Section of the Home page UI, designing both in Lo-Fi and Hi-Fi formats.

Attached below are their respective Figma links: 
Hi-Fi: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1565%3A19520
Lo-Fi: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1591%3A32879
