### ISSUE TITLE
Build failed because of webpack errors

### ISSUE THREAD

**Issue by rhedwan** [zuri-training/auth_wiki_team_1_project#184]
<img width="1440" alt="Screenshot 2022-08-13 at 11 48 14 AM" src="https://user-images.githubusercontent.com/48237269/184480331-ddf5a79e-3476-4daa-b2af-a0e75e595f27.png">

Kindly fix this on your local machine

**Comment by unclemfon** [comment]
Alright, seen. Thank you.

**Comment by Nifilat** [comment]
@rhedwan Hello, did you run npm install before the build, cause the module is in the package.json file. Please keep me updated.

**Comment by Nifilat** [comment]
It has been updated, could you please retry it now @rhedwan

**Comment by rhedwan** [comment]
@Nifilat  I ran npm install first
