### ISSUE TITLE
create CRUD for Reaction model

### ISSUE THREAD

**Issue by adilimudassir** [zuri-training/auth_wiki_team_1_project#73]

**Comment by TimmyKwesi** [comment]
@adilimudassir this has yet to be assigned. I've been trying but I'm not sure how it's supposed
to work. A little clarification would be great🙏

**Comment by Ayomide0123** [comment]
I "attempted " it.

**Comment by unclemfon** [comment]
Okay, Timmy and Ayomide. It has been assigned to both of you

**Comment by TimmyKwesi** [comment]
@themfon I think Ayomide has done it already. Mr. Ahmad already approved it too.

**Comment by unclemfon** [comment]
Alright! Thanks. Well done guys!
