### ISSUE TITLE
About Us Page Design

### ISSUE THREAD

**Issue by Angelo-Ufelle** [zuri-training/auth_wiki_team_1_project#84]
Design the About Us web page user interface

**Comment by DesiignBro** [comment]
Yeah,. this has been completed @Angelo-Ufelle

**Comment by MeeYah66** [comment]
I designed the hero page of the about us web UI using the style guide provided.

https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1458%3A18665
