### ISSUE TITLE
Home Page Design

### ISSUE THREAD

**Issue by Angelo-Ufelle** [zuri-training/auth_wiki_team_1_project#85]
Design the user interface for Home Page

**Comment by DesiignBro** [comment]
I designed the Hero section of the Homepage Web Ui using the style guide that was provided.

Attached below is the Figma link to the Homepage Frame:
https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1458%3A17078

**Comment by DesiignBro** [comment]
I also worked on the Hero section of the Homepage UI for the mobile version using the style guide that was provided.

Attached below is the Figma link to the Mobile Homepage Frame:
https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1458%3A22632

**Comment by olayinka12345** [comment]
I designed the Lo-Fi and Hi-Fi of the body of the homepage Web UI which includes the About us section, our core features and the contact us page



Attached below is the Figma link to the Lo-Fi and Hi-Fi of the Homepage Frame:
Lo-Fi Link: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1591%3A32879
Hi-Fi Link: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1565%3A18748

**Comment by olayinka12345** [comment]
.
