### ISSUE TITLE
User Research

### ISSUE THREAD

**Issue by Angelo-Ufelle** [zuri-training/auth_wiki_team_1_project#86]
Conduct a user research

**Comment by Favourjubilee** [comment]
Completed the User Research;

Did the Organized Notes.
Gave out Survey Question forms
Conducted Interviews
Empathy Map.
Pain Points.
Idea Prioritization Matrix.
User Persona Template

https://www.figma.com/file/ZNDDuLEf8wk0ilayBK6lC6/User-Research?node-id=0%3A1
