### ISSUE TITLE
Sign-in/Sign-up/forgot password pages

### ISSUE THREAD

**Issue by Angelo-Ufelle** [zuri-training/auth_wiki_team_1_project#89]
Design a user interface for the pages

**Comment by MakkyD** [comment]
I worked on the signup, signIn and the Forgot password pages, other screens like the loader screen and the "password changed successfully screen" were also designed by me as there were screens embedded in my task assigned. 

Attached below is the Lowfi to the web view of the signup, signin and Forgot password screens

Web-View-Lowfi-  https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1602%3A20245

**Comment by MakkyD** [comment]
Attached below is the link to the Hi-Fidelity designs(web view) for the Signup, SignIn and Forgot password page i was assigned and worked on.

Web-View-HiFi-  https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1567%3A18748

**Comment by MakkyD** [comment]
done
