### ISSUE TITLE
Create a style guide

### ISSUE THREAD

**Issue by unclemfon** [zuri-training/auth_wiki_team_1_project#90]

**Comment by DesiignBro** [comment]
I created the Style Guide for use in the design of both the Web and Mobile User Interfaces of the project idea. This includes Typography, Colours, Spacing, Grid System, Iconography, Button System, Input System & Alerts/Notifications.

Link to Style Guide: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1691%3A20854
