### ISSUE TITLE
Design Library Page

### ISSUE THREAD

**Issue by unclemfon** [zuri-training/auth_wiki_team_1_project#93]
Update Code Samples on the page when you get it from the backend team

**Comment by DesiignBro** [comment]
Yeah. I've implemented the code samples on the UI. Design is pending reviews

**Comment by theotherfaceofA** [comment]
I designed the main page for the unauthenticated user for the library. 

Attached below is the figma link to the frame: 
https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1458%3A21327

**Comment by theotherfaceofA** [comment]
I also designed the "view more" page that prompts unauthenticated users to sign up before getting access to other features in the library.

Attached below is the figma link to the frame:
https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1458%3A21507

**Comment by theotherfaceofA** [comment]
I worked on mobile responsiveness for the "comments" page of the library for unauthenticated users that prompts them to log in/sign up before leaving a comment.

Attached below is the figma link to the frame:
https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1461%3A18495

**Comment by theotherfaceofA** [comment]
I also worked on mobile responsiveness of the main page for the unauthenticated users for the library.

Attached below is the figma link to the frame:
https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1461%3A18104

**Comment by theotherfaceofA** [comment]
I also designed for mobile responsiveness of the "view more" page that prompts unauthenticated users to login/sign up before getting access to other features in the library.

Attached below is the figma link to the frame:
https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1490%3A19451

**Comment by Jeremy124124** [comment]
I designed the desktop Web UI of the authenticated user on the Library page, below are the links to the frame
lo-fi figma link: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1603%3A20246
Hi-fi figma link: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1567%3A19093

**Comment by theotherfaceofA** [comment]
I worked on the desktop Web UI of the unauthenticated user on the Library page, below are links to the frames
Lo-fi figma link: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1722%3A20845
Hi-fi figma link: https://www.figma.com/file/t4QbYjbcsnhtRYHLUN9AIh/Team-1-Figma-Board?node-id=1722%3A20846
